name: Real_emeralds
version: 1.0-SNAPSHOT
main: de.vendettagroup.real_emeralds.Main
api-version: 1.17
authors: [ felix2300 ]
description: Adds an tag to mined emeralds, so you can difference between mined and traded emeralds

commands:
  realemerald: