name: Real_emeralds
version: 2.0
main: de.vendettagroup.real_emeralds.Main
api-version: 1.17
authors: [ felix2300 ]
description: Adds an tag to mined emeralds, so you can difference between mined and traded emeralds

commands:
  reload:
    description: Reloads the plugin! (Reloads the config file)
    permission: realemerald.admin
  clear-lore-log:
    description: Clears the lore log!
    permission: realemerald.admin